stages:
  - test
  - deploy

image: node:lts
variables:
  CLOUDAMQP_URL: amqp://127.0.0.1/
services:
  - rabbitmq
before_script:
  - npm install

package_version:
  stage: test
  script:
    - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    - PUBLISHED_VERSION=$(npm view nodejsmq version)
    - if [ "$PUBLISHED_VERSION" == "$PACKAGE_VERSION" ]; then exit 1; fi

test:
  stage: test
  script:
    - sleep 40s
    - npm run-script test

lint:
  stage: test
  script:
    - npm run-script tsc

publish:
  stage: deploy
  only:
    - master
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish