stages:
  - test
  - deploy

image: node
variables:
  CLOUDAMQP_URL: amqp://rabbitmq/
services:
  - rabbitmq
before_script:
  - npm install

package_version:
  stage: test
  script:
    - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    - PUBLISHED_VERSION=$(npm view nodejsmq version)
    - if [ "$PUBLISHED_VERSION" == "$PACKAGE_VERSION" ]; then exit 1; fi

test:
  stage: test
  script: 
    - npm run-script test

deploy_github:
  only:
    - master
  stage: deploy
  image: debian
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git remote rm origin
    - git remote add origin https://drgroot:$GITHUB_TOKEN@github.com/drgroot/$CI_PROJECT_NAME.git
    - git push origin $CI_COMMIT_REF_NAME --force

publish:
  stage: deploy
  only:
    - master
  image: node
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  script:
    - npm run-script build
    - npm publish